### PR TITLE
Fix: focus selected tab content

### LINKED ISSUE #530: Changing RDP tabs should focus the new tab
When I am working on an RDP session and I change tabs, for some reason keyboard focus is retained by the previous tab. Whatever I type is affecting the other (hidden) tab until I click on the screen.

Changing tabs should always immediately focus the keyboard on the displayed session.

### PR DESCRIPTION
**Pull request by itagagaki**
This resolve #530
This is not perfect but almost fine.

---

In the following case, keystrokes do not reach the active window on the remote host:

1. Connect to Host A --> keystrokes reach the active window on Host A.
2. Connect to Host B in the same host window --> keystrokes reach the active window on Host B.
3. Click the Host A tab --> the content switches, but keystrokes do not reach either Host A or Host B.

The cause is unknown. However, if you make activate a remote window by clicking on it with the mouse, keystrokes will reach it. After that, switching tabs will correctly send keystrokes to the active window of the host that has been switched to.

---

For now, I think it's best to merge this fix and file the above case as a new issue.
(P.S. Filed. --> #1052)

I have left the code for AxMsRdpClient09Host.FocusOnMe() as-is since I don't understand its intention, but the application behaves as expected even without calling it (except for the aforementioned issue).

### CODE REVIEW

**Comment by itagagaki** [comment]
Although the above case is related, it can be considered a separate issue.
The following simple steps using version 1.2.1 also reproduce the issue.

1. Connect to an RDP host.
2. Click on another local client window to activate/focus it.
3. Click the tab of the RDP host.

The focus will not return to the RDP.

**Comment by VShawn** [comment]
tricky but works

p.s. AxMsRdpClient09Host.FocusOnMe() is also used to set focus on RDP.

**Comment by itagagaki** [comment]
> p.s. AxMsRdpClient09Host.FocusOnMe() is also used to set focus on RDP.

okay

File: Ui/View/Host/TabWindowViewModel.cs [hunk 1]
```diff
@@ -82,6 +96,16 @@ public TabItemViewModel? SelectedItem
             get => _selectedItem;
             set
             {
+                _timer_ObserveTabSwitching.Stop();
+
+                // Get effective window of the current tab content.
+                _hWndTabContent = IntPtr.Zero;
+                IntPtr hWndParent = Win32Api.FindWindow(null, this.Title);
```
Comment (itagagaki) [inline Ui/View/Host/TabWindowViewModel.cs]: What if there are multiple tabs with the same title? This is a concern.
